import {
  Tournament,
  Team,
  Player,
  Match,
  ScorecardInnings,
  PlayerMatchStats,
  User,
} from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user-admin',
    name: 'Dr. K. Srinivas (Admin)',
    email: 'admin@ctms.org',
    password: 'admin',
    role: 'admin',
    created_at: '2026-09-01T10:00:00Z',
  },
  {
    id: 'user-manager',
    name: 'Vikram Shekar (Coastal Kings)',
    email: 'manager@coastalkings.com',
    password: 'manager',
    role: 'team_manager',
    team_id: 'team-coastal-kings',
    created_at: '2026-09-02T11:00:00Z',
  },
  {
    id: 'user-scorer',
    name: 'Manoj Kumar (Official Scorer)',
    email: 'scorer@ctms.org',
    password: 'scorer',
    role: 'scorer',
    created_at: '2026-09-03T09:30:00Z',
  },
  {
    id: 'user-viewer',
    name: 'Guest Cricket Fan',
    email: 'viewer@ctms.org',
    password: 'viewer',
    role: 'viewer',
    created_at: '2026-09-04T08:00:00Z',
  },
];

export const INITIAL_TOURNAMENTS: Tournament[] = [
  {
    id: 'tourn-cpl-2026',
    name: 'Campus Premier League 2026',
    description: 'The flagship inter-collegiate T20 cricket tournament bringing together top university teams for the coveted Silver Bat trophy.',
    location: 'Central University Cricket Grounds, Vizag',
    start_date: '2026-09-10',
    end_date: '2026-09-25',
    format: 'T20',
    status: 'Ongoing',
    max_teams: 6,
    created_at: '2026-09-01T09:00:00Z',
  },
  {
    id: 'tourn-monsoon-cup',
    name: 'Inter-Departmental Shield 2026',
    description: 'Annual monsoon 50-overs ODI tournament for academic departments and affiliated institutions.',
    location: 'North Campus Oval',
    start_date: '2026-10-05',
    end_date: '2026-10-20',
    format: 'ODI',
    status: 'Upcoming',
    max_teams: 8,
    created_at: '2026-09-05T14:00:00Z',
  },
  {
    id: 'tourn-winter-trophy-2025',
    name: 'All-State Varsity Challenge 2025',
    description: 'Previous edition championship held across state engineering and arts colleges.',
    location: 'Municipal Cricket Stadium',
    start_date: '2025-11-10',
    end_date: '2025-11-28',
    format: 'T20',
    status: 'Completed',
    max_teams: 4,
    created_at: '2025-10-15T10:00:00Z',
  },
];

export const INITIAL_TEAMS: Team[] = [
  {
    id: 'team-vizag-warriors',
    tournament_id: 'tourn-cpl-2026',
    name: 'Vizag Warriors',
    short_name: 'VZW',
    logo: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=160&auto=format&fit=crop&q=80',
    captain: 'Arjun Verma',
    coach: 'Ramesh Chandra',
    manager: 'Suresh Naidu',
    contact: 'warriors@cpl.edu',
    created_at: '2026-09-02T10:00:00Z',
  },
  {
    id: 'team-coastal-kings',
    tournament_id: 'tourn-cpl-2026',
    name: 'Coastal Kings',
    short_name: 'CSK',
    logo: 'https://images.unsplash.com/photo-1531415074868-036b1c57e329?w=160&auto=format&fit=crop&q=80',
    captain: 'Rohit Reddy',
    coach: 'Vikram Shekar',
    manager: 'Vikram Shekar',
    contact: 'manager@coastalkings.com',
    created_at: '2026-09-02T11:00:00Z',
  },
  {
    id: 'team-andhra-strikers',
    tournament_id: 'tourn-cpl-2026',
    name: 'Andhra Strikers',
    short_name: 'ADS',
    logo: 'https://images.unsplash.com/photo-1587280501635-68a0e82cd5ff?w=160&auto=format&fit=crop&q=80',
    captain: 'Kalyan Roy',
    coach: 'Anand Murthy',
    manager: 'Praveen Kumar',
    contact: 'strikers@cpl.edu',
    created_at: '2026-09-02T12:00:00Z',
  },
  {
    id: 'team-campus-titans',
    tournament_id: 'tourn-cpl-2026',
    name: 'Campus Titans',
    short_name: 'CPT',
    logo: 'https://images.unsplash.com/photo-1512719994953-eabf50895df7?w=160&auto=format&fit=crop&q=80',
    captain: 'Devendra Sharma',
    coach: 'Sunil Varma',
    manager: 'Rajesh Gupta',
    contact: 'titans@cpl.edu',
    created_at: '2026-09-02T13:00:00Z',
  },
];

export const INITIAL_PLAYERS: Player[] = [
  // Vizag Warriors
  {
    id: 'p-vzw-1',
    team_id: 'team-vizag-warriors',
    name: 'Arjun Verma',
    date_of_birth: '2003-04-12',
    age: 23,
    jersey_number: 18,
    role: 'Batsman',
    batting_style: 'Right-hand bat',
    bowling_style: 'Right-arm medium',
    contact: 'arjun.v@cpl.edu',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=160&auto=format&fit=crop&q=80',
    created_at: '2026-09-03T10:00:00Z',
  },
  {
    id: 'p-vzw-2',
    team_id: 'team-vizag-warriors',
    name: 'Praneeth Rao',
    date_of_birth: '2004-01-15',
    age: 22,
    jersey_number: 7,
    role: 'Wicketkeeper',
    batting_style: 'Right-hand bat',
    bowling_style: 'None',
    contact: 'praneeth.r@cpl.edu',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=160&auto=format&fit=crop&q=80',
    created_at: '2026-09-03T10:05:00Z',
  },
  {
    id: 'p-vzw-3',
    team_id: 'team-vizag-warriors',
    name: 'Sandeep Yadav',
    date_of_birth: '2003-08-20',
    age: 23,
    jersey_number: 99,
    role: 'All-Rounder',
    batting_style: 'Left-hand bat',
    bowling_style: 'Right-arm off-spin',
    contact: 'sandeep.y@cpl.edu',
    photo: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=160&auto=format&fit=crop&q=80',
    created_at: '2026-09-03T10:10:00Z',
  },
  {
    id: 'p-vzw-4',
    team_id: 'team-vizag-warriors',
    name: 'Kiran Deep',
    date_of_birth: '2004-11-05',
    age: 21,
    jersey_number: 24,
    role: 'Bowler',
    batting_style: 'Right-hand bat',
    bowling_style: 'Right-arm fast',
    contact: 'kiran.d@cpl.edu',
    photo: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=160&auto=format&fit=crop&q=80',
    created_at: '2026-09-03T10:15:00Z',
  },
  {
    id: 'p-vzw-5',
    team_id: 'team-vizag-warriors',
    name: 'Naveen Kumar',
    date_of_birth: '2003-06-30',
    age: 23,
    jersey_number: 11,
    role: 'Bowler',
    batting_style: 'Right-hand bat',
    bowling_style: 'Left-arm orthodox',
    contact: 'naveen.k@cpl.edu',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=160&auto=format&fit=crop&q=80',
    created_at: '2026-09-03T10:20:00Z',
  },

  // Coastal Kings
  {
    id: 'p-csk-1',
    team_id: 'team-coastal-kings',
    name: 'Rohit Reddy',
    date_of_birth: '2002-12-05',
    age: 23,
    jersey_number: 45,
    role: 'Batsman',
    batting_style: 'Right-hand bat',
    bowling_style: 'Right-arm off break',
    contact: 'rohit.r@cpl.edu',
    photo: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=160&auto=format&fit=crop&q=80',
    created_at: '2026-09-03T11:00:00Z',
  },
  {
    id: 'p-csk-2',
    team_id: 'team-coastal-kings',
    name: 'Murali Krishna',
    date_of_birth: '2003-03-22',
    age: 23,
    jersey_number: 10,
    role: 'Wicketkeeper',
    batting_style: 'Left-hand bat',
    bowling_style: 'None',
    contact: 'murali.k@cpl.edu',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=160&auto=format&fit=crop&q=80',
    created_at: '2026-09-03T11:05:00Z',
  },
  {
    id: 'p-csk-3',
    team_id: 'team-coastal-kings',
    name: 'Gautam Anand',
    date_of_birth: '2004-09-18',
    age: 21,
    jersey_number: 33,
    role: 'All-Rounder',
    batting_style: 'Right-hand bat',
    bowling_style: 'Right-arm medium fast',
    contact: 'gautam.a@cpl.edu',
    photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=160&auto=format&fit=crop&q=80',
    created_at: '2026-09-03T11:10:00Z',
  },
  {
    id: 'p-csk-4',
    team_id: 'team-coastal-kings',
    name: 'Venkat Somesh',
    date_of_birth: '2003-07-14',
    age: 23,
    jersey_number: 8,
    role: 'Bowler',
    batting_style: 'Right-hand bat',
    bowling_style: 'Right-arm leg spin',
    contact: 'venkat.s@cpl.edu',
    photo: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=160&auto=format&fit=crop&q=80',
    created_at: '2026-09-03T11:15:00Z',
  },
  {
    id: 'p-csk-5',
    team_id: 'team-coastal-kings',
    name: 'Farhan Ali',
    date_of_birth: '2004-02-28',
    age: 22,
    jersey_number: 19,
    role: 'Bowler',
    batting_style: 'Right-hand bat',
    bowling_style: 'Right-arm fast',
    contact: 'farhan.a@cpl.edu',
    photo: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=160&auto=format&fit=crop&q=80',
    created_at: '2026-09-03T11:20:00Z',
  },

  // Andhra Strikers
  {
    id: 'p-ads-1',
    team_id: 'team-andhra-strikers',
    name: 'Kalyan Roy',
    date_of_birth: '2003-05-19',
    age: 23,
    jersey_number: 77,
    role: 'Batsman',
    batting_style: 'Left-hand bat',
    bowling_style: 'Right-arm medium',
    contact: 'kalyan.r@cpl.edu',
    photo: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=160&auto=format&fit=crop&q=80',
    created_at: '2026-09-03T12:00:00Z',
  },
  {
    id: 'p-ads-2',
    team_id: 'team-andhra-strikers',
    name: 'Ravi Teja',
    date_of_birth: '2004-08-11',
    age: 22,
    jersey_number: 14,
    role: 'All-Rounder',
    batting_style: 'Right-hand bat',
    bowling_style: 'Right-arm off spin',
    contact: 'ravi.t@cpl.edu',
    photo: 'https://images.unsplash.com/photo-1513956589380-bad6acb9b9d4?w=160&auto=format&fit=crop&q=80',
    created_at: '2026-09-03T12:05:00Z',
  },
  {
    id: 'p-ads-3',
    team_id: 'team-andhra-strikers',
    name: 'Ashwin Nair',
    date_of_birth: '2003-10-02',
    age: 22,
    jersey_number: 21,
    role: 'Bowler',
    batting_style: 'Right-hand bat',
    bowling_style: 'Right-arm fast',
    contact: 'ashwin.n@cpl.edu',
    photo: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=160&auto=format&fit=crop&q=80',
    created_at: '2026-09-03T12:10:00Z',
  },

  // Campus Titans
  {
    id: 'p-cpt-1',
    team_id: 'team-campus-titans',
    name: 'Devendra Sharma',
    date_of_birth: '2003-02-14',
    age: 23,
    jersey_number: 9,
    role: 'Batsman',
    batting_style: 'Right-hand bat',
    bowling_style: 'Right-arm leg spin',
    contact: 'devendra.s@cpl.edu',
    photo: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=160&auto=format&fit=crop&q=80',
    created_at: '2026-09-03T13:00:00Z',
  },
  {
    id: 'p-cpt-2',
    team_id: 'team-campus-titans',
    name: 'Aditya Sen',
    date_of_birth: '2004-04-25',
    age: 22,
    jersey_number: 17,
    role: 'Wicketkeeper',
    batting_style: 'Right-hand bat',
    bowling_style: 'None',
    contact: 'aditya.s@cpl.edu',
    photo: 'https://images.unsplash.com/photo-1520409364224-63400afe26e5?w=160&auto=format&fit=crop&q=80',
    created_at: '2026-09-03T13:05:00Z',
  },
  {
    id: 'p-cpt-3',
    team_id: 'team-campus-titans',
    name: 'Harsh Vardhan',
    date_of_birth: '2003-12-01',
    age: 22,
    jersey_number: 88,
    role: 'Bowler',
    batting_style: 'Left-hand bat',
    bowling_style: 'Left-arm fast',
    contact: 'harsh.v@cpl.edu',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=160&auto=format&fit=crop&q=80',
    created_at: '2026-09-03T13:10:00Z',
  },
];

export const INITIAL_MATCHES: Match[] = [
  {
    id: 'match-1',
    tournament_id: 'tourn-cpl-2026',
    team1_id: 'team-vizag-warriors',
    team2_id: 'team-coastal-kings',
    match_date: '2026-09-12',
    match_time: '14:00',
    venue: 'University Stadium Pitch A',
    match_type: 'League',
    status: 'Completed',
    winner_team_id: 'team-vizag-warriors',
    result_description: 'Vizag Warriors won by 18 runs',
    toss_winner_team_id: 'team-vizag-warriors',
    toss_decision: 'bat',
    current_innings: 2,
    created_at: '2026-09-04T10:00:00Z',
  },
  {
    id: 'match-2',
    tournament_id: 'tourn-cpl-2026',
    team1_id: 'team-andhra-strikers',
    team2_id: 'team-campus-titans',
    match_date: '2026-09-14',
    match_time: '18:00',
    venue: 'University Stadium Floodlit Arena',
    match_type: 'League',
    status: 'Completed',
    winner_team_id: 'team-campus-titans',
    result_description: 'Campus Titans won by 4 wickets (8 balls remaining)',
    toss_winner_team_id: 'team-campus-titans',
    toss_decision: 'bowl',
    current_innings: 2,
    created_at: '2026-09-04T10:15:00Z',
  },
  {
    id: 'match-3',
    tournament_id: 'tourn-cpl-2026',
    team1_id: 'team-coastal-kings',
    team2_id: 'team-andhra-strikers',
    match_date: '2026-09-17',
    match_time: '14:30',
    venue: 'University Stadium Pitch B',
    match_type: 'League',
    status: 'Live',
    toss_winner_team_id: 'team-coastal-kings',
    toss_decision: 'bat',
    current_innings: 1,
    created_at: '2026-09-04T10:30:00Z',
  },
  {
    id: 'match-4',
    tournament_id: 'tourn-cpl-2026',
    team1_id: 'team-vizag-warriors',
    team2_id: 'team-campus-titans',
    match_date: '2026-09-20',
    match_time: '15:00',
    venue: 'University Stadium Pitch A',
    match_type: 'League',
    status: 'Scheduled',
    created_at: '2026-09-04T10:45:00Z',
  },
  {
    id: 'match-5',
    tournament_id: 'tourn-cpl-2026',
    team1_id: 'team-coastal-kings',
    team2_id: 'team-campus-titans',
    match_date: '2026-09-22',
    match_time: '16:00',
    venue: 'University Stadium Pitch A',
    match_type: 'League',
    status: 'Scheduled',
    created_at: '2026-09-04T11:00:00Z',
  },
  {
    id: 'match-6',
    tournament_id: 'tourn-cpl-2026',
    team1_id: 'team-vizag-warriors',
    team2_id: 'team-andhra-strikers',
    match_date: '2026-09-24',
    match_time: '15:00',
    venue: 'University Stadium Pitch A',
    match_type: 'League',
    status: 'Scheduled',
    created_at: '2026-09-04T11:15:00Z',
  },
];

export const INITIAL_SCORECARDS: ScorecardInnings[] = [
  // Match 1 - Innings 1 (Vizag Warriors Batting)
  {
    id: 'sc-m1-inn1',
    match_id: 'match-1',
    innings_number: 1,
    batting_team_id: 'team-vizag-warriors',
    bowling_team_id: 'team-coastal-kings',
    runs: 174,
    wickets: 5,
    overs: 20.0,
    balls: 120,
    extras: { wides: 6, no_balls: 2, byes: 1, leg_byes: 3, total: 12 },
    result: '174/5 (20.0 Ov)',
    created_at: '2026-09-12T16:00:00Z',
  },
  // Match 1 - Innings 2 (Coastal Kings Batting)
  {
    id: 'sc-m1-inn2',
    match_id: 'match-1',
    innings_number: 2,
    batting_team_id: 'team-coastal-kings',
    bowling_team_id: 'team-vizag-warriors',
    runs: 156,
    wickets: 8,
    overs: 20.0,
    balls: 120,
    extras: { wides: 5, no_balls: 1, byes: 0, leg_byes: 2, total: 8 },
    result: '156/8 (20.0 Ov)',
    created_at: '2026-09-12T18:00:00Z',
  },

  // Match 2 - Innings 1 (Andhra Strikers Batting)
  {
    id: 'sc-m2-inn1',
    match_id: 'match-2',
    innings_number: 1,
    batting_team_id: 'team-andhra-strikers',
    bowling_team_id: 'team-campus-titans',
    runs: 142,
    wickets: 9,
    overs: 20.0,
    balls: 120,
    extras: { wides: 7, no_balls: 1, byes: 2, leg_byes: 1, total: 11 },
    result: '142/9 (20.0 Ov)',
    created_at: '2026-09-14T20:00:00Z',
  },
  // Match 2 - Innings 2 (Campus Titans Batting)
  {
    id: 'sc-m2-inn2',
    match_id: 'match-2',
    innings_number: 2,
    batting_team_id: 'team-campus-titans',
    bowling_team_id: 'team-andhra-strikers',
    runs: 146,
    wickets: 6,
    overs: 18.4,
    balls: 112,
    extras: { wides: 4, no_balls: 2, byes: 0, leg_byes: 3, total: 9 },
    result: '146/6 (18.4 Ov)',
    created_at: '2026-09-14T21:45:00Z',
  },

  // Match 3 (Live Match) - Innings 1 in progress (Coastal Kings Batting)
  {
    id: 'sc-m3-inn1',
    match_id: 'match-3',
    innings_number: 1,
    batting_team_id: 'team-coastal-kings',
    bowling_team_id: 'team-andhra-strikers',
    runs: 128,
    wickets: 3,
    overs: 14.2,
    balls: 86,
    extras: { wides: 4, no_balls: 1, byes: 2, leg_byes: 1, total: 8 },
    result: '128/3 in 14.2 Ov',
    created_at: '2026-09-17T15:00:00Z',
  },
];

export const INITIAL_PLAYER_STATS: PlayerMatchStats[] = [
  // Match 1: Arjun Verma (VZW) Batting
  {
    id: 'stat-m1-arjun',
    match_id: 'match-1',
    player_id: 'p-vzw-1',
    player_name: 'Arjun Verma',
    team_id: 'team-vizag-warriors',
    innings_number: 1,
    runs: 68,
    balls: 44,
    fours: 7,
    sixes: 3,
    is_out: true,
    dismissal_info: 'c Murali b Venkat',
    strike_rate: 154.55,
    overs_bowled: 0,
    balls_bowled: 0,
    maidens: 0,
    runs_conceded: 0,
    wickets: 0,
    economy: 0,
    created_at: '2026-09-12T16:00:00Z',
  },
  // Match 1: Sandeep Yadav (VZW) Batting & Bowling
  {
    id: 'stat-m1-sandeep',
    match_id: 'match-1',
    player_id: 'p-vzw-3',
    player_name: 'Sandeep Yadav',
    team_id: 'team-vizag-warriors',
    innings_number: 1,
    runs: 41,
    balls: 26,
    fours: 4,
    sixes: 1,
    is_out: false,
    dismissal_info: 'not out',
    strike_rate: 157.69,
    overs_bowled: 4,
    balls_bowled: 24,
    maidens: 0,
    runs_conceded: 28,
    wickets: 2,
    economy: 7.0,
    created_at: '2026-09-12T16:00:00Z',
  },
  // Match 1: Kiran Deep (VZW) Bowling
  {
    id: 'stat-m1-kiran',
    match_id: 'match-1',
    player_id: 'p-vzw-4',
    player_name: 'Kiran Deep',
    team_id: 'team-vizag-warriors',
    innings_number: 2,
    runs: 2,
    balls: 3,
    fours: 0,
    sixes: 0,
    is_out: false,
    strike_rate: 66.67,
    overs_bowled: 4,
    balls_bowled: 24,
    maidens: 1,
    runs_conceded: 22,
    wickets: 3,
    economy: 5.5,
    created_at: '2026-09-12T18:00:00Z',
  },

  // Match 1: Rohit Reddy (CSK) Batting
  {
    id: 'stat-m1-rohit',
    match_id: 'match-1',
    player_id: 'p-csk-1',
    player_name: 'Rohit Reddy',
    team_id: 'team-coastal-kings',
    innings_number: 2,
    runs: 54,
    balls: 38,
    fours: 6,
    sixes: 2,
    is_out: true,
    dismissal_info: 'b Kiran Deep',
    strike_rate: 142.11,
    overs_bowled: 0,
    balls_bowled: 0,
    maidens: 0,
    runs_conceded: 0,
    wickets: 0,
    economy: 0,
    created_at: '2026-09-12T18:00:00Z',
  },
  // Match 1: Venkat Somesh (CSK) Bowling
  {
    id: 'stat-m1-venkat',
    match_id: 'match-1',
    player_id: 'p-csk-4',
    player_name: 'Venkat Somesh',
    team_id: 'team-coastal-kings',
    innings_number: 1,
    runs: 8,
    balls: 6,
    fours: 1,
    sixes: 0,
    is_out: true,
    strike_rate: 133.33,
    overs_bowled: 4,
    balls_bowled: 24,
    maidens: 0,
    runs_conceded: 31,
    wickets: 2,
    economy: 7.75,
    created_at: '2026-09-12T16:00:00Z',
  },

  // Match 2: Devendra Sharma (CPT)
  {
    id: 'stat-m2-devendra',
    match_id: 'match-2',
    player_id: 'p-cpt-1',
    player_name: 'Devendra Sharma',
    team_id: 'team-campus-titans',
    innings_number: 2,
    runs: 62,
    balls: 41,
    fours: 8,
    sixes: 2,
    is_out: false,
    dismissal_info: 'not out',
    strike_rate: 151.22,
    overs_bowled: 2,
    balls_bowled: 12,
    maidens: 0,
    runs_conceded: 16,
    wickets: 1,
    economy: 8.0,
    created_at: '2026-09-14T21:45:00Z',
  },
  // Match 2: Kalyan Roy (ADS)
  {
    id: 'stat-m2-kalyan',
    match_id: 'match-2',
    player_id: 'p-ads-1',
    player_name: 'Kalyan Roy',
    team_id: 'team-andhra-strikers',
    innings_number: 1,
    runs: 48,
    balls: 35,
    fours: 5,
    sixes: 1,
    is_out: true,
    dismissal_info: 'c & b Harsh',
    strike_rate: 137.14,
    overs_bowled: 3,
    balls_bowled: 18,
    maidens: 0,
    runs_conceded: 24,
    wickets: 1,
    economy: 8.0,
    created_at: '2026-09-14T20:00:00Z',
  },

  // Match 3 (Live): Rohit Reddy (CSK)
  {
    id: 'stat-m3-rohit',
    match_id: 'match-3',
    player_id: 'p-csk-1',
    player_name: 'Rohit Reddy',
    team_id: 'team-coastal-kings',
    innings_number: 1,
    runs: 56,
    balls: 37,
    fours: 6,
    sixes: 2,
    is_out: false,
    dismissal_info: 'batting',
    strike_rate: 151.35,
    overs_bowled: 0,
    balls_bowled: 0,
    maidens: 0,
    runs_conceded: 0,
    wickets: 0,
    economy: 0,
    created_at: '2026-09-17T15:00:00Z',
  },
  // Match 3 (Live): Gautam Anand (CSK)
  {
    id: 'stat-m3-gautam',
    match_id: 'match-3',
    player_id: 'p-csk-3',
    player_name: 'Gautam Anand',
    team_id: 'team-coastal-kings',
    innings_number: 1,
    runs: 34,
    balls: 22,
    fours: 3,
    sixes: 1,
    is_out: false,
    dismissal_info: 'batting',
    strike_rate: 154.55,
    overs_bowled: 0,
    balls_bowled: 0,
    maidens: 0,
    runs_conceded: 0,
    wickets: 0,
    economy: 0,
    created_at: '2026-09-17T15:00:00Z',
  },
];
